version: '1'

services:
  zoo1:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zoo1
    container_name: zoo1
    ports:
      - "2181:2181"
    networks:
      - kafka-net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo1:2888:3888

  kafka1:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9999:9999"
    networks:
      - kafka-net
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9092"
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
      KAFKAJS_NO_PARTITIONER_WARNING: 1
    depends_on:
      - zoo1

  backend:
    command: sleep infinity
    container_name: backend
    build:
      context: .
      dockerfile: ${BACKEND_DOCKER_FILE}
    ports:
      - "3000:3000"
    volumes:
      - '${BACKEND_VOLUME}:/home'
    working_dir: /home
    networks:
      - kafka-net
    depends_on:
      - kafka1
      - zoo1
    environment:
      KAFKA_BROKER: kafka1:9092
      KAFKAJS_NO_PARTITIONER_WARNING: 1

  frontend:
    command: sleep infinity
    container_name: frontend
    build:
      context: .
      dockerfile: ${FRONTEND_DOCKER_FILE}
    ports:
      - "4000:4000"
    volumes:
      - '${FRONTEND_VOLUME}:/home'
    working_dir: /home
    networks:
      - kafka-net
    depends_on:
      - kafka1
      - zoo1
    environment:
      KAFKA_BROKER: kafka1:9092
      KAFKAJS_NO_PARTITIONER_WARNING: 1

networks:
  kafka-net:
